### ISSUE TITLE
Pleas add included SBR Firmware Files

### ISSUE THREAD

**Issue by hburkert** [sungrow-firmware/firmware#1]
[SBR128_1_SBRBCU-S_22011.01.13_20220811.zip](https://github.com/sungrow-firmware/firmware/files/10785915/SBR128_1_SBRBCU-S_22011.01.13_20220811.zip)
[SBR128_1_SBRBCU-S_22011.01.14_20221111.zip](https://github.com/sungrow-firmware/firmware/files/10785916/SBR128_1_SBRBCU-S_22011.01.14_20221111.zip)
[SBR128_1_SBRBCU-S_22011.01.16_unpack.zip](https://github.com/sungrow-firmware/firmware/files/10785918/SBR128_1_SBRBCU-S_22011.01.16_unpack.zip)
[SBR128_1_SBRBCU-S_22011.01.17_unpack.zip](https://github.com/sungrow-firmware/firmware/files/10785919/SBR128_1_SBRBCU-S_22011.01.17_unpack.zip)
[SBR160_1_SBRBCU-S_22011.01.13_20220811.zip](https://github.com/sungrow-firmware/firmware/files/10785920/SBR160_1_SBRBCU-S_22011.01.13_20220811.zip)
[SBR160_1_SBRBCU-S_22011.01.14_20221111.zip](https://github.com/sungrow-firmware/firmware/files/10785921/SBR160_1_SBRBCU-S_22011.01.14_20221111.zip)
[SBR160_1_SBRBCU-S_22011.01.16_unpack.zip](https://github.com/sungrow-firmware/firmware/files/10785922/SBR160_1_SBRBCU-S_22011.01.16_unpack.zip)
[SBR160_1_SBRBCU-S_22011.01.17_unpack.zip](https://github.com/sungrow-firmware/firmware/files/10785923/SBR160_1_SBRBCU-S_22011.01.17_unpack.zip)
[SBR192_1_SBRBCU-S_22011.01.13_20220811.zip](https://github.com/sungrow-firmware/firmware/files/10785924/SBR192_1_SBRBCU-S_22011.01.13_20220811.zip)
[SBR192_1_SBRBCU-S_22011.01.14_20221111.zip](https://github.com/sungrow-firmware/firmware/files/10785925/SBR192_1_SBRBCU-S_22011.01.14_20221111.zip)
[SBR192_1_SBRBCU-S_22011.01.16_unpack.zip](https://github.com/sungrow-firmware/firmware/files/10785926/SBR192_1_SBRBCU-S_22011.01.16_unpack.zip)
[SBR192_1_SBRBCU-S_22011.01.17_unpack.zip](https://github.com/sungrow-firmware/firmware/files/10785927/SBR192_1_SBRBCU-S_22011.01.17_unpack.zip)
[SBR224_1_SBRBCU-S_22011.01.13_20220811.zip](https://github.com/sungrow-firmware/firmware/files/10785928/SBR224_1_SBRBCU-S_22011.01.13_20220811.zip)
[SBR224_1_SBRBCU-S_22011.01.14_20221111.zip](https://github.com/sungrow-firmware/firmware/files/10785929/SBR224_1_SBRBCU-S_22011.01.14_20221111.zip)
[SBR224_1_SBRBCU-S_22011.01.16_unpack.zip](https://github.com/sungrow-firmware/firmware/files/10785930/SBR224_1_SBRBCU-S_22011.01.16_unpack.zip)
[SBR224_1_SBRBCU-S_22011.01.17_unpack.zip](https://github.com/sungrow-firmware/firmware/files/10785931/SBR224_1_SBRBCU-S_22011.01.17_unpack.zip)
[SBR256_1_SBRBCU-S_22011.01.13_20220811.zip](https://github.com/sungrow-firmware/firmware/files/10785932/SBR256_1_SBRBCU-S_22011.01.13_20220811.zip)
[SBR256_1_SBRBCU-S_22011.01.14_20221111.zip](https://github.com/sungrow-firmware/firmware/files/10785933/SBR256_1_SBRBCU-S_22011.01.14_20221111.zip)
[SBR256_1_SBRBCU-S_22011.01.16_unpack.zip](https://github.com/sungrow-firmware/firmware/files/10785935/SBR256_1_SBRBCU-S_22011.01.16_unpack.zip)
[SBR256_1_SBRBCU-S_22011.01.17_unpack.zip](https://github.com/sungrow-firmware/firmware/files/10785936/SBR256_1_SBRBCU-S_22011.01.17_unpack.zip)

**Comment by sungrow-firmware** [comment]
done
