### ISSUE TITLE
I need auto-restart...

### ISSUE THREAD

**Issue by atakankan** [sungrow-firmware/firmware#11]
The device does not respond while communicating via Modbus protocol. 
This occurs when the device operates for a long time. 
Turning it off and on again fixes it.

Is there a way to auto-restart?

**Comment by Gnarfoz** [comment]
Sorry, but this is a project to collect Sungrow firmware files, not a support forum.

**Comment by sungrow-firmware** [comment]
I am not aware of any auto-restart functionality. If your inverter also has an internal LAN port, use this instead of the Winet interface. The internal port has a more stable Modbus connection.
