### ISSUE TITLE
Looking for SH5K firmware

### ISSUE THREAD

**Issue by brettbrooks** [sungrow-firmware/firmware#12]
Hi,

I've looking for SH5K-V13_V47.zip or SH5K-V13_V48.zip.
It's for the oldest SH5K, before the SH5K-20 and SH5K-30. It is no longer on iSolarCloud because it's no longer supported but I have an SH5K that's never been updated. 

Thanks.

**Comment by sungrow-firmware** [comment]
I'm sorry, but I started collecting the firmware last year and I only have access to the firmware available from iSolarCloud.
