### ISSUE TITLE
New version for SH10RT-V112 missing

### ISSUE THREAD

**Issue by djmoonshine** [sungrow-firmware/firmware#3]
Named SAPPHIRE-H_B000.V000.P006-20230302.zip in iSolarCloud
Can you find and upload it? 
Or how do I download it from Sungrow? Can't find the files downloded with the app.

**Comment by sungrow-firmware** [comment]
I've added the filed with 74b77532c53efa93744b4af72565840a5d2d2faf
I download the files, using the app internal API.
