### ISSUE TITLE
Latest firmware for SH10RT V11

### ISSUE THREAD

**Issue by StefanRied** [sungrow-firmware/firmware#7]
Hi Sungrow

I see that you uploaded SAPPHIRE-H_B001.V000.P005-20231027 for some SH10RT hybrid inverters. 
However, it is not uploaded for the SH10RT V11
Is this same file from the V112 working?

Thanks

**Comment by dervomsee** [comment]
I dont think so. Sungrows renamed several times their firmware repo. 
In my optinion the file should be moved to the folder "SH10RT" and this firmware is compatible to your inverter: https://github.com/sungrow-firmware/firmware/tree/main/Hybrid%20Inverter/SH10RT

**Comment by sungrow-firmware** [comment]
I moved the files to one folder.
